### ISSUE TITLE
支持rtmp转发吗？

### ISSUE THREAD

**Issue by MoonLikeWater** [yy1261633791/rtsp-web-converter#10]

**Comment by yy1261633791** [comment]
支持从RTMP转成FLV

**Comment by MoonLikeWater** [comment]
用了cctv的rtmp流，转发报错。
`[rtmp @ 0000000020e6c100] Cannot open connection tcp://116.213.200.53:1935?listen&listen_timeout=705032704
[rtmp @ 0000000020e6c100] Cannot open connection tcp://116.213.200.53:1935?listen&listen_timeout=705032704
2020-12-10 11:06:22.273 [Thread-12] ERROR com.converter.factories.ConverterFactories - avformat_open_input() error -10049: Could not open input "rtmp://116.213.200.53/tslsChannelLive/PCG0DuD/live". (Has setFormat() been called?)
org.bytedeco.javacv.FrameGrabber$Exception: avformat_open_input() error -10049: Could not open input "rtmp://116.213.200.53/tslsChannelLive/PCG0DuD/live". (Has setFormat() been called?)
        at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:853) ~[javacv-1.5.1.jar!/:1.5.1]
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:785) ~[javacv-1.5.1.jar!/:1.5.1]
        at com.converter.factories.ConverterFactories.run(ConverterFactories.java:85) ~[classes!/:2.0.5.RELEASE]
2020-12-10 11:06:22.273 [Thread-12] INFO  com.converter.factories.ConverterFactories - this url:rtmp://116.213.200.53/tslsChannelLive/PCG0DuD/live converterFactories exit
[rtmp @ 0000000020e6c100] Cannot open connection tcp://116.213.200.53:1935?listen&listen_timeout=705032704
[rtmp @ 0000000020e6c100] Cannot open connection tcp://116.213.200.53:1935?listen&listen_timeout=705032704
2020-12-10 11:08:03.689 [Thread-13] ERROR com.converter.factories.ConverterFactories - avformat_open_input() error -10049: Could not open input "rtmp://116.213.200.53/tslsChannelLive/PCG0DuD/live". (Has setFormat() been called?)
org.bytedeco.javacv.FrameGrabber$Exception: avformat_open_input() error -10049: Could not open input "rtmp://116.213.200.53/tslsChannelLive/PCG0DuD/live". (Has setFormat() been called?)
        at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:853) ~[javacv-1.5.1.jar!/:1.5.1]
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:785) ~[javacv-1.5.1.jar!/:1.5.1]
        at com.converter.factories.ConverterFactories.run(ConverterFactories.java:85) ~[classes!/:2.0.5.RELEASE]
2020-12-10 11:08:03.689 [Thread-13] INFO  com.converter.factories.ConverterFactories - this url:rtmp://116.213.200.53/tslsChannelLive/PCG0DuD/live converterFactories exit`

**Comment by MoonLikeWater** [comment]
`[rtmp @ 0000000020e6c100] Cannot open connection tcp://58.200.131.2:1935?listen&listen_timeout=705032704
[rtmp @ 0000000020e6c100] Cannot open connection tcp://58.200.131.2:1935?listen&listen_timeout=705032704
2020-12-10 11:10:55.768 [Thread-15] ERROR com.converter.factories.ConverterFactories - avformat_open_input() error -10049: Could not open input "rtmp://58.200.131.2:1935/livetv/cctv1". (Has setFormat() been called?)
org.bytedeco.javacv.FrameGrabber$Exception: avformat_open_input() error -10049: Could not open input "rtmp://58.200.131.2:1935/livetv/cctv1". (Has setFormat() been called?)
        at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:853) ~[javacv-1.5.1.jar!/:1.5.1]
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:785) ~[javacv-1.5.1.jar!/:1.5.1]
        at com.converter.factories.ConverterFactories.run(ConverterFactories.java:85) ~[classes!/:2.0.5.RELEASE]
2020-12-10 11:10:55.769 [Thread-15] INFO  com.converter.factories.ConverterFactories - this url:rtmp://58.200.131.2:1935/livetv/cctv1 converterFactories exit`

**Comment by yy1261633791** [comment]
rtmp://58.200.131.2:1935/livetv/cctv1 你这个流我也打不开呀

**Comment by MoonLikeWater** [comment]
用vlc播放器可以打开的，可以试一下。

**Comment by yy1261633791** [comment]
有个BUG
ConverterFactories类82行
			if ("rtsp".equals(url.substring(0, 4))) {
				grabber.setOption("rtsp_transport", "tcp");
				grabber.setOption("stimeout", "5000000");
			} else {
				grabber.setOption("timeout", "50000000");
			}
改成
                       if ("rtsp".equals(url.substring(0, 4))) {
				grabber.setOption("rtsp_transport", "tcp");
				grabber.setOption("stimeout", "5000000");
			}

**Comment by yy1261633791** [comment]
rtmp://202.69.69.180:443/webcast/bshdlive-pc   测试这个流通过

**Comment by MoonLikeWater** [comment]
你提交下呗，我拉下最新的代码重新试一下。

**Comment by yy1261633791** [comment]
你拉吧

**Comment by MoonLikeWater** [comment]
rtmp可以转了，十分感谢！！！！！
