### ISSUE TITLE
栈溢出异常

### ISSUE THREAD

**Issue by fshang** [yy1261633791/rtsp-web-converter#2]
前端 ：flv.js
后端 idea运行环境
现象：使用10分钟左右，服务报stackoverflow异常

**Comment by yy1261633791** [comment]
能给点详细的报错信息吗

**Comment by harperMa** [comment]
> 能给点详细的报错信息吗

        at org.apache.catalina.connector.CoyoteOutputStream.flush(CoyoteOutputSt
ream.java:118) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at com.fasterxml.jackson.core.json.UTF8JsonGenerator.flush(UTF8JsonGener
ator.java:1100) ~[jackson-core-2.9.6.jar!/:2.9.6]
        at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.j
ava:915) ~[jackson-databind-2.9.6.jar!/:2.9.6]
        at org.springframework.http.converter.json.AbstractJackson2HttpMessageCo
nverter.writeInternal(AbstractJackson2HttpMessageConverter.java:285) ~[spring-we
b-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at org.springframework.http.converter.AbstractGenericHttpMessageConverte
r.write(AbstractGenericHttpMessageConverter.java:102) ~[spring-web-5.0.9.RELEASE
.jar!/:5.0.9.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.AbstractMessage
ConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMeth
odProcessor.java:272) ~[spring-webmvc-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.HttpEntityMetho
dProcessor.handleReturnValue(HttpEntityMethodProcessor.java:224) ~[spring-webmvc
-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at org.springframework.web.method.support.HandlerMethodReturnValueHandle
rComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:82) ~
[spring-web-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocabl
eHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:119) ~[spring-
webmvc-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingH
andlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:891) ~[sprin
g-webmvc-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingH
andlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-web
mvc-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapt
er.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.0.9.RELEASE.ja
r!/:5.0.9.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(Dispatch
erServlet.java:991) ~[spring-webmvc-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(Dispatche
rServlet.java:925) ~[spring-webmvc-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(Frame
workServlet.java:974) ~[spring-webmvc-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServl
et.java:866) ~[spring-webmvc-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) ~[tomcat
-embed-core-8.5.34.jar!/:8.5.34]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkSer
vlet.java:851) ~[spring-webmvc-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[tomcat
-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:231) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:166) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDisp
atcher.java:728) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationD
ispatcher.java:591) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDis
patcher.java:527) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.j
ava:389) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.j
ava:254) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValv
e.java:349) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.j
ava:175) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.j
ava:81) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineVal
ve.java:87) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapt
er.java:230) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:2
45) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLig
ht.java:53) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(Abstract
Protocol.java:806) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpo
int.java:1498) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBas
e.java:49) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?
:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[
?:1.8.0_181]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskTh
read.java:61) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.io.IOException: 您的主机中的软件中止了一个已建立的连接。
        at sun.nio.ch.SocketDispatcher.write0(Native Method) ~[?:1.8.0_181]
        at sun.nio.ch.SocketDispatcher.write(Unknown Source) ~[?:1.8.0_181]
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(Unknown Source) ~[?:1.8.0_181
]
        at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_181]
        at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_181]
        at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:134) ~[to
mcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.tomcat.util.net.NioBlockingSelector.write(NioBlockingSelec
tor.java:101) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.tomcat.util.net.NioSelectorPool.write(NioSelectorPool.java
:157) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.doWrite(NioEn
dpoint.java:1306) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.tomcat.util.net.SocketWrapperBase.doWrite(SocketWrapperBas
e.java:726) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.tomcat.util.net.SocketWrapperBase.writeBlocking(SocketWrap
perBase.java:496) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.tomcat.util.net.SocketWrapperBase.write(SocketWrapperBase.
java:434) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.coyote.http11.Http11OutputBuffer$SocketOutputBuffer.doWrit
e(Http11OutputBuffer.java:623) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.coyote.http11.filters.ChunkedOutputFilter.doWrite(ChunkedO
utputFilter.java:121) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.coyote.http11.Http11OutputBuffer.doWrite(Http11OutputBuffe
r.java:225) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.coyote.Response.doWrite(Response.java:541) ~[tomcat-embed-
core-8.5.34.jar!/:8.5.34]
        at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffe
r.java:351) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        ... 43 more
2020-09-21 16:45:47.500 [Thread-7] INFO  com.converter.factories.ConverterFactor
ies - 移除一个输出
2020-09-21 16:45:47.500 [Thread-7] INFO  com.converter.factories.ConverterFactor
ies - 没有输出退出
2020-09-21 16:45:47.563 [http-nio-8081-exec-3] ERROR com.converter.controller.ad
vice.GlobleExceptionHandler - Could not find acceptable representation
org.springframework.web.HttpMediaTypeNotAcceptableException: Could not find acce
ptable representation
        at org.springframework.web.servlet.mvc.method.annotation.AbstractMessage
ConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMeth
odProcessor.java:288) ~[spring-webmvc-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.HttpEntityMetho
dProcessor.handleReturnValue(HttpEntityMethodProcessor.java:224) ~[spring-webmvc
-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at org.springframework.web.method.support.HandlerMethodReturnValueHandle
rComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:82) ~
[spring-web-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocabl
eHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:119) ~[spring-
webmvc-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingH
andlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:891) ~[sprin
g-webmvc-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingH
andlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-web
mvc-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapt
er.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.0.9.RELEASE.ja
r!/:5.0.9.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(Dispatch
erServlet.java:991) ~[spring-webmvc-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(Dispatche
rServlet.java:925) ~[spring-webmvc-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(Frame
workServlet.java:974) ~[spring-webmvc-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServl
et.java:866) ~[spring-webmvc-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) ~[tomcat
-embed-core-8.5.34.jar!/:8.5.34]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkSer
vlet.java:851) ~[spring-webmvc-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[tomcat
-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:231) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:166) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDisp
atcher.java:728) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationD
ispatcher.java:591) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDis
patcher.java:527) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.j
ava:389) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.j
ava:254) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValv
e.java:349) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.catalina.core.AsyncContextImpl.setErrorState(AsyncContextI
mpl.java:424) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapt
er.java:176) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:2
45) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLig
ht.java:53) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(Abstract
Protocol.java:806) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpo
int.java:1498) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBas
e.java:49) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?
:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[
?:1.8.0_181]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskTh
read.java:61) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
2020-09-21 16:45:47.576 [http-nio-8081-exec-3] WARN  org.springframework.web.ser
vlet.mvc.method.annotation.ExceptionHandlerExceptionResolver - Failed to invoke
@ExceptionHandler method: public com.converter.result.JsonResult com.converter.c
ontroller.advice.GlobleExceptionHandler.errorHandler(org.springframework.web.Htt
pMediaTypeException)
org.springframework.web.HttpMediaTypeNotAcceptableException: Could not find acce
ptable representation
        at org.springframework.web.servlet.mvc.method.annotation.AbstractMessage
ConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMeth
odProcessor.java:288) ~[spring-webmvc-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestResponse
BodyMethodProcessor.handleReturnValue(RequestResponseBodyMethodProcessor.java:18
0) ~[spring-webmvc-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at org.springframework.web.method.support.HandlerMethodReturnValueHandle
rComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:82) ~
[spring-web-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocabl
eHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:119) ~[spring-
webmvc-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ExceptionHandle
rExceptionResolver.doResolveHandlerMethodException(ExceptionHandlerExceptionReso
lver.java:404) ~[spring-webmvc-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at org.springframework.web.servlet.handler.AbstractHandlerMethodExceptio
nResolver.doResolveException(AbstractHandlerMethodExceptionResolver.java:61) ~[s
pring-webmvc-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at org.springframework.web.servlet.handler.AbstractHandlerExceptionResol
ver.resolveException(AbstractHandlerExceptionResolver.java:136) ~[spring-webmvc-
5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at org.springframework.web.servlet.handler.HandlerExceptionResolverCompo
site.resolveException(HandlerExceptionResolverComposite.java:78) ~[spring-webmvc
-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.processHandlerExcep
tion(DispatcherServlet.java:1255) ~[spring-webmvc-5.0.9.RELEASE.jar!/:5.0.9.RELE
ASE]
        at org.springframework.web.servlet.DispatcherServlet.processDispatchResu
lt(DispatcherServlet.java:1062) ~[spring-webmvc-5.0.9.RELEASE.jar!/:5.0.9.RELEAS
E]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(Dispatch
erServlet.java:1008) ~[spring-webmvc-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(Dispatche
rServlet.java:925) ~[spring-webmvc-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(Frame
workServlet.java:974) ~[spring-webmvc-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServl
et.java:866) ~[spring-webmvc-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) ~[tomcat
-embed-core-8.5.34.jar!/:8.5.34]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkSer
vlet.java:851) ~[spring-webmvc-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[tomcat
-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:231) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:166) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDisp
atcher.java:728) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationD
ispatcher.java:591) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDis
patcher.java:527) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.j
ava:389) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.j
ava:254) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValv
e.java:349) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.catalina.core.AsyncContextImpl.setErrorState(AsyncContextI
mpl.java:424) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapt
er.java:176) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:2
45) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLig
ht.java:53) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(Abstract
Protocol.java:806) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpo
int.java:1498) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBas
e.java:49) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?
:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[
?:1.8.0_181]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskTh
read.java:61) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
